# Generated by Django 4.1 on 2022-08-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='english_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='english_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='hungarian_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='hungarian_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='menu_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucategory'),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='swedish_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='swedish_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
